export { default as Camera } from './Camera'
export { default as Instagram } from './Instagram'
export { default as Logo } from './Logo'
export { default as More } from './More'
export { default as Send } from './Send'